### PR TITLE
Use Lightning save/loading functions in example

### PR DESCRIPTION
**Pull request by SeanNaren**
## What changes are proposed in this pull request?

Use PL saving/loading functions to handle ddp case silently! 

## How is this patch tested?

Running mnist_model.py code. Need to still test to ensure it works in deployment. 

### Is this a user-facing change?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow TorchServe Deployment Plugin users.

(Details in 1-2 sentences. You can just refer to another PR with a description if this PR is part of a larger change.)

### What component(s) does this PR affect?
Components
- [ ] `area/deploy`: Main deployment plugin logic
- [ ] `area/build`: Build and test infrastructure for MLflow TorchServe Deployment Plugin
- [ ] `area/docs`: MLflow TorchServe Deployment Plugin documentation pages
- [x] `area/examples`: Example code

### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [ ] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

**Comment by shrinath-suresh** [comment]
@SeanNaren Thanks for PR. Using Pytorch Lightning Checkpoint mechanism resolves the ddp issue. However, for using checkpoints there are few more points to think about. 

1. By using `mlflow.pytorch` library, supporting artifacts such as `requirements.txt` or `vocabulary files` can be stored along with the model using [requirements_file and extra_files parameter](https://www.mlflow.org/docs/latest/_modules/mlflow/pytorch.html#log_model). In case of HF Bert examples, these files are needed for deployment - [Bert news classification Example](https://github.com/mlflow/mlflow-torchserve/blob/cc9fd0f0d7aa24c9e784a4390fee8c7467183e7b/examples/BertNewsClassification/news_classifier.py#L397). The MLModel file inside the models directory, contains more information about the current artifacts. This makes the job easy for deployment plugin to associate with the supporting files and directory.

2. `mlflow.pytorch` library is used to store the model into mlflow. Currently `mlflow.pytorch` library only supports, storing the entire model into mlflow. Since, loading back the entire model from mlflow causes error in ddp environment, we have saved the model explicitly as [state dict](https://github.com/mlflow/mlflow-torchserve/blob/cc9fd0f0d7aa24c9e784a4390fee8c7467183e7b/examples/MNIST/mnist_model.py#L297) and loaded it back in the[ handler file](https://github.com/mlflow/mlflow-torchserve/blob/cc9fd0f0d7aa24c9e784a4390fee8c7467183e7b/examples/MNIST/mnist_handler.py#L36). 

The actual user flow for End to End deployment cycle would be as follows. 

1. User trains the model using `[mlflow.pytorch.autolog()]`(https://www.mlflow.org/docs/latest/_modules/mlflow/pytorch.html#autolog)
2. At the end of the training model gets saved into mlflow
3. User [Registers](https://www.mlflow.org/docs/latest/model-registry.html) the model into mlflow
4. When user provides the corresponding registered model uri - deployment plugin downloads the model and deploys it into torchserve. 

And for doing this seamless process we need to store the model as state_dict. Hence, one option would be to enhance the `mlflow.pytorch` libray to save the model as state dict. Please let us know your thoughts.

**Comment by SeanNaren** [comment]
thanks @shrinath-suresh!

This is great, If I'm understanding correct you'd like to do `mlflow.pytorch.save_model()` to handle this logic internally?

Will need to investigate the save/load functions within mlflow but it should be possible to have a hook within their code to do this.

**Comment by shrinath-suresh** [comment]
> thanks @shrinath-suresh!
> 
> This is great, If I'm understanding correct you'd like to do `mlflow.pytorch.save_model()` to handle this logic internally?
> 
> Will need to investigate the save/load functions within mlflow but it should be possible to have a hook within their code to do this.

Tried out a sample implementation - https://github.com/chauhang/mlflow/pull/33

**Comment by SeanNaren** [comment]
Ah nice! I still think there is an issue of not saving all trainer arguments for PL etc. Also it would be nice for the save_model function to completely rely on the checkpoint dumped via pytorch-lightning rather than requiring to work this out itself. What do you think of something like this?

```python
...
if trainer.global_rank == 0:
    checkpoint = trainer.create_checkpoint()
    mlflow.pytorch.save_model(checkpoint, 'model.pth')
```

**Comment by chauhang** [comment]
@SeanNaren  So there are two use cases here:

1. Model training - ability to checkpoint and restart training from the last checkpoint. Here using the PTL trainer checkpoint will be appropriate. Looking at the latest docs for the trainer checkpoint, can you please clarify how it handles the parameters for DDP case -- eg things like how many GPUs was the training launched on so that DDP run can be resumed from last checkpoint without any process group loading related errors?

2. Model inferencing - after the training is completed, we need to prepare the model for running inference. Speed of loading the model and reducing overall latency are important in this case. So we need option to only save the state_dict for optimized loading of the model for inference. This is the scenario that we are tackling for this example. Do you see any issues from PTL perspective with using state_dict approach for this case?

Best Regards,
Geeta

**Comment by SeanNaren** [comment]
> @SeanNaren So there are two use cases here:
> 
> 1. Model training - ability to checkpoint and restart training from the last checkpoint. Here using the PTL trainer checkpoint will be appropriate. Looking at the latest docs for the trainer checkpoint, can you please clarify how it handles the parameters for DDP case -- eg things like how many GPUs was the training launched on so that DDP run can be resumed from last checkpoint without any process group loading related errors?
> 2. Model inferencing - after the training is completed, we need to prepare the model for running inference. Speed of loading the model and reducing overall latency are important in this case. So we need option to only save the state_dict for optimized loading of the model for inference. This is the scenario that we are tackling for this example. Do you see any issues from PTL perspective with using state_dict approach for this case?
> 
> Best Regards,
> Geeta

Thanks for the explanation, cleared a lot of for me :)

I would still suggest using PL's internal save checkpoint function as this PR has done for the serving portion, because it also handles things like passing correct args to the class/ddp support etc. (We're in the process of updating our doc examples to reflect this as well, just going through iterations to make sure everything is explained properly!)

Let me dump the information here for you @chauhang and we're currently working on clarifying all this in one place in PL ASAP:

The Trainer save checkpoint function automatically handles any internal accelerator based logic including DDP. 

DDP means that your training script is running on multiple processes at the same time. if you don't use the saving functionality of pytorch lightning (as currently done) this means that each process will try to save the model, which can lead to a lot of issues unless that is the expected behaviour. we handle this automatically in the backend by ensuring we only save on one process (the main process).

When loading however, each process loads the model from the saved file as expected.

In addition, DDP works by wrapping your model with a DDP class (that's how PyTorch handles communication on top of your model). Our trainer function will automatically extract the actual module you want to save, without any of the distributed wrapper. This is why when attempting saving the entire model results in an error (process groups not initialized).

If you _really_ want to use `state_dict` to save, you have to add additional logic outside of the code base. First you have to ensure the write saving logic. If you want the model to be saved once (in the main process):

```python
if trainer.global_rank == 0:
   torch.save(...)
```

The next thing as you found out is that you have to remove the parallel wrapper or you run into the parallel groups are not initialized error:

```python
if trainer.global_rank == 0:
    state_dict = trainer.get_model().state_dict()
    torch.save(...)
```

This is all boilerplate that we're handling within lightning, but if you want complete control for any reason these are examples on how to do so.

**Comment by SeanNaren** [comment]
Hey @shrinath-suresh any updates here? I modified the save function to only save the weights via flag. Let me know if this works :)

**Comment by shrinath-suresh** [comment]
> Hey @shrinath-suresh any updates here? I modified the save function to only save the weights via flag. Let me know if this works :)

We are in process of updating the `mlflow.pytorch` library to use state_dict. And updating the MNIST example to use `mlflow.pytorch.log_state_dict()`. 

@chauhang Can you please let us know the direction. We are updating the the library to use state_dict. Do we need to add an example to save/load the model using PTL checkpoints ?

**Comment by SeanNaren** [comment]
That would be good :) thanks for the update!

**Pull request closed without merging**
